version: '2'
services:
  redis_primary:
#    image: jamtur01/redis_primary
    build: redis_primary/.
    hostname: redis_primary
  redis_replica1:
#    image: jamtur01/redis_replica
    build: redis_replica/.
    hostname: redis_replica1
    links: 
      - redis_primary:redis_primary
  redis_replica2:
#    image: jamtur01/redis_replica
    build: redis_replica/.
    hostname: redis_replica2
    links: 
      - redis_primary:redis_primary
  nodeapp:
#    image: jamtur01/nodejs
    build: nodejs/.
    ports:
      - 3000:3000
    links:
      - redis_primary:redis_primary
  logstash:
#    image: jamtur01/logstash
    build: logstash/.
    volumes_from: 
      - nodeapp
      - redis_primary
    
      
